name: hello
runs:
  using: "composite"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: print
        run: |
          echo in test-action3/action.yml  in main
          echo pwd
          echo "$pwd"
          echo $pwd
          
